---
title: "Collaborator's Take"
---

***

> Current Events: April 14, 2016 to April 16, 2016

<font size="4"> In a world where news breaks so frequently and the time frame for an event to be deemed "current" is arguably shorter than a day, April 2016 might seem a lot farther back in the past than it actually was. Believe it or not, there were actually quite a few notable events around the world that took place in this short span. Our goal in this section was to try and tie the emotions of twitter users at the time to events they were responding to, hoping to make logical connections about why tweets express the sentiments that they do. </font>

<font size="4"> That being said, some of the most notable events from April 14 to April 16 of 2016 include: The Golden State Warriors finishing the NBA season with the best record in history, Hillary Clinton and Bernie Sanders' have a contentious debate in New York City, deadly earthquakes strike Japan, North Korea fails in a missile-launch attempt, and public health officials confirmed a link between the Zika virus and the devastating birth defect microcephaly. Obviously this is not a comprehensive list, but is sufficient enough to say that the average twitter user would have heard of at least one the events. </font>

***

> What conclusions can we draw?

<font size="4"> The list of events above is also sufficient enough such that they would elicit the whole range of emotions from twitter users that we used in our analyses (anger, anticipation, disgust, fear, joy sadness, surprise, trust). Thus, we can generally expect specific tweets with certain sentiments to correlate with at least some of these events (Example: a tweet expressing joy has decent chance of being about the Warriors' season, and a tweet expressing sadness has decent chance of being about the earthquakes in Japan). </font>

<font size="4"> As expected, we see more highly concentrated tweet distributions in more populated areas. Perhaps less expected, we see that the distribution of all the sentiments is relatively equal across all the regions of the U.S. From this, we can make a general inference about information spread across the U.S.: it's fairly equal, and not particularly subject to geographical discrimination. Sentiment prevalence is (almost surpisingly) consistent across every state, which leads us to believe that twitter users react to what they see and hear about in approximately the same way. The only thing that changes (again, as expected) is number and spread of users themselves, but the distribution of sentiments is highly comparable between any two subsections of the U.S. </font>

***

> Acknowledgement of the limitations of Twitter:

<font size="4"> Since neither Twitter or our data analyses will ever be perfect, there are some limitations we'd like to address. Twitter, like many other account-based social media sites, is full of bots, which are essentially non-human users capable of generating tweets and other content (but frequently produce spam and other irrelevant information). A quick glance at the dataset shows that there is very likely a large number of spam-bots posing as users in the dataset, something that is very difficult to control for, especially when these bots are capable of producing content that is hard to distinguish from what a human user might write. That being said, a sentiment analysis of twitterbots (which is intrinsically a part of our analysis) can yield unpredicatble  results. However, we did pick up on a rather noticeable trend, particularly when examining word and sentiment frequencies. The word "job" is by far the most prevalent word, and "trust" is by far the most prevalent sentiment. It is not unreasonable to say that many of twitterbots in this dataset are responsible for both of these occurrences. With that in mind, the rampant predominance of "jobs" and "trust" becomes understandable, and further analyses of word frequencies and sentiment dispersion become more intuitive (especially when looking at the sentiment plots with "trust" removed). However, this is not meant to discredit the "job" and "trust" terms altogether. Certain events, notably the presidential debate, could spark a significant discussion about jobs and give a sturdy platform for expressing trust (in a candidate, for example).  </font> 
